<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-99.9.9">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andreas Bogossian &amp; Markus Kruth">

<title>Bayesian Analysis of Aviation Accidents</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-be2dad9397c9b99732ed2a04f2c65f62.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3470f103b9553535cd37a6a812bcfecd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#problem" id="toc-problem" class="nav-link" data-scroll-target="#problem">Problem</a></li>
  <li><a href="#main-modeling-idea" id="toc-main-modeling-idea" class="nav-link" data-scroll-target="#main-modeling-idea">Main Modeling Idea</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  </ul></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a>
  <ul class="collapse">
  <li><a href="#crashes-over-time" id="toc-crashes-over-time" class="nav-link" data-scroll-target="#crashes-over-time">Crashes Over Time</a></li>
  <li><a href="#fatalities-over-time" id="toc-fatalities-over-time" class="nav-link" data-scroll-target="#fatalities-over-time">Fatalities Over Time</a></li>
  <li><a href="#fatality-rate-over-time" id="toc-fatality-rate-over-time" class="nav-link" data-scroll-target="#fatality-rate-over-time">Fatality Rate Over Time</a></li>
  <li><a href="#empirical-fatality-rates-by-manufacturer" id="toc-empirical-fatality-rates-by-manufacturer" class="nav-link" data-scroll-target="#empirical-fatality-rates-by-manufacturer">Empirical Fatality Rates by Manufacturer</a></li>
  </ul></li>
  <li><a href="#data-modeling" id="toc-data-modeling" class="nav-link" data-scroll-target="#data-modeling">Data Modeling</a>
  <ul class="collapse">
  <li><a href="#complete-pooling-non-hierarchical" id="toc-complete-pooling-non-hierarchical" class="nav-link" data-scroll-target="#complete-pooling-non-hierarchical">Complete Pooling (Non-Hierarchical)</a></li>
  <li><a href="#no-pooling-non-hierarchical" id="toc-no-pooling-non-hierarchical" class="nav-link" data-scroll-target="#no-pooling-non-hierarchical">No Pooling (Non-Hierarchical)</a></li>
  <li><a href="#partial-pooling-hierarchical" id="toc-partial-pooling-hierarchical" class="nav-link" data-scroll-target="#partial-pooling-hierarchical">Partial Pooling (Hierarchical)</a></li>
  <li><a href="#prior-selection" id="toc-prior-selection" class="nav-link" data-scroll-target="#prior-selection">Prior Selection</a>
  <ul class="collapse">
  <li><a href="#global-intercept" id="toc-global-intercept" class="nav-link" data-scroll-target="#global-intercept">Global Intercept</a></li>
  <li><a href="#global-year-coefficient" id="toc-global-year-coefficient" class="nav-link" data-scroll-target="#global-year-coefficient">Global Year Coefficient</a></li>
  <li><a href="#manufacturer-level-priors-no-pooling" id="toc-manufacturer-level-priors-no-pooling" class="nav-link" data-scroll-target="#manufacturer-level-priors-no-pooling">Manufacturer-Level Priors (No Pooling)</a></li>
  <li><a href="#group-level-standard-deviation-partial-pooling" id="toc-group-level-standard-deviation-partial-pooling" class="nav-link" data-scroll-target="#group-level-standard-deviation-partial-pooling">Group-Level Standard Deviation (Partial Pooling)</a></li>
  <li><a href="#correlation-coefficient-rho" id="toc-correlation-coefficient-rho" class="nav-link" data-scroll-target="#correlation-coefficient-rho">Correlation Coefficient <span class="math inline">\(\rho\)</span></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#complete-pooling-non-hierarchical-model" id="toc-complete-pooling-non-hierarchical-model" class="nav-link" data-scroll-target="#complete-pooling-non-hierarchical-model">Complete pooling (non-hierarchical model)</a>
  <ul class="collapse">
  <li><a href="#complete-pooling-model" id="toc-complete-pooling-model" class="nav-link" data-scroll-target="#complete-pooling-model">Complete Pooling Model</a>
  <ul class="collapse">
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#convergence-diagnostics" id="toc-convergence-diagnostics" class="nav-link" data-scroll-target="#convergence-diagnostics">Convergence Diagnostics</a></li>
  <li><a href="#posterior-predictive-check" id="toc-posterior-predictive-check" class="nav-link" data-scroll-target="#posterior-predictive-check">Posterior Predictive Check</a></li>
  <li><a href="#predictions-over-time" id="toc-predictions-over-time" class="nav-link" data-scroll-target="#predictions-over-time">Predictions Over Time</a></li>
  <li><a href="#prior-sensitivity-analysis" id="toc-prior-sensitivity-analysis" class="nav-link" data-scroll-target="#prior-sensitivity-analysis">Prior Sensitivity Analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#no-pooling-non-hierarchical-model" id="toc-no-pooling-non-hierarchical-model" class="nav-link" data-scroll-target="#no-pooling-non-hierarchical-model">No pooling (non-hierarchical model)</a>
  <ul class="collapse">
  <li><a href="#no-pooling-model" id="toc-no-pooling-model" class="nav-link" data-scroll-target="#no-pooling-model">No Pooling Model</a>
  <ul class="collapse">
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model</a></li>
  <li><a href="#convergence-diagnostics-1" id="toc-convergence-diagnostics-1" class="nav-link" data-scroll-target="#convergence-diagnostics-1">Convergence Diagnostics</a></li>
  <li><a href="#posterior-predictive-check-1" id="toc-posterior-predictive-check-1" class="nav-link" data-scroll-target="#posterior-predictive-check-1">Posterior Predictive Check</a></li>
  <li><a href="#predictions-by-manufacturer" id="toc-predictions-by-manufacturer" class="nav-link" data-scroll-target="#predictions-by-manufacturer">Predictions by Manufacturer</a></li>
  <li><a href="#prior-sensitivity-analysis-1" id="toc-prior-sensitivity-analysis-1" class="nav-link" data-scroll-target="#prior-sensitivity-analysis-1">Prior Sensitivity Analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#partial-pooling-hierarchical-model" id="toc-partial-pooling-hierarchical-model" class="nav-link" data-scroll-target="#partial-pooling-hierarchical-model">Partial pooling (hierarchical model)</a>
  <ul class="collapse">
  <li><a href="#partial-pooling-model" id="toc-partial-pooling-model" class="nav-link" data-scroll-target="#partial-pooling-model">Partial Pooling Model</a>
  <ul class="collapse">
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2">Model</a></li>
  <li><a href="#convergence-diagnostics-2" id="toc-convergence-diagnostics-2" class="nav-link" data-scroll-target="#convergence-diagnostics-2">Convergence Diagnostics</a></li>
  <li><a href="#posterior-predictive-check-2" id="toc-posterior-predictive-check-2" class="nav-link" data-scroll-target="#posterior-predictive-check-2">Posterior Predictive Check</a></li>
  <li><a href="#prior-sensitivity-analysis-2" id="toc-prior-sensitivity-analysis-2" class="nav-link" data-scroll-target="#prior-sensitivity-analysis-2">Prior Sensitivity Analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model comparison</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#self-reflection" id="toc-self-reflection" class="nav-link" data-scroll-target="#self-reflection">Self Reflection</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bayesian Analysis of Aviation Accidents</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andreas Bogossian &amp; Markus Kruth </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This project models the fatality rates of airplane crashes from 1975 to 2024. We use non-hierarchical and hierarchical Bayesian models with the airplane manufacturer as the grouping variable in the hierarchical model. Specifically, we compare two non-hierarchical models (complete pooling and no pooling) against one hierarchical model (partial pooling).</p>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">Motivation</h2>
<p>Aviation has undergone massive developments since the first commercial flight in 1914. Airplane safety has always been the top priority for airlines; a single airplane crash will drive away customers to safer perceived airlines and, of course, cost lives. Although this priority of making airplanes as safe as possible has significantly reduced the number of crashes over the years, accidents still continue to occur.</p>
<p>Not all accidents are the same; survivability in crashes varies significantly. Understanding which factors influence survivability in crashes remains crucial for manufacturers and airlines seeking to minimize the loss of life. While accident prevention remains the most important priority, understanding the fatality patterns when accidents do occur is equally important in discussions of airplane safety.</p>
</section>
<section id="problem" class="level2">
<h2 class="anchored" data-anchor-id="problem">Problem</h2>
<p>When aviation accidents occur, the fatality rates vary significantly — from incidents where all passengers survive to catastrophic losses of everyone on board. This variation raises critical questions: Has the likelihood of surviving an airplane crash improved over time? Do certain airplane manufacturers demonstrate consistently higher crash survival rates than others? How much of the variation in crash fatality rates can be attributed to crash-specific details of individual accidents versus inherent airplane characteristics? These are questions that we hope to answer in our report.</p>
</section>
<section id="main-modeling-idea" class="level2">
<h2 class="anchored" data-anchor-id="main-modeling-idea">Main Modeling Idea</h2>
<p>We address these questions using hierarchical and non-hierarchical Bayesian modeling of fatality rates across aviation accidents from 1975 to 2024. We assume that aircraft from the same manufacturer share some of the same characteristics, such as similar design choices, engineering approaches, and safety systems. We still account for the overall similarity between all aircraft by including a global population-level distribution. We compare a partial pooling model against two baselines: complete pooling and no pooling.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>The dataset was obtained from a Kaggle repository created by Jonathan Ogwumike <span class="citation" data-cites="jogwums2023aircrashes"><a href="#ref-jogwums2023aircrashes" role="doc-biblioref">[1]</a></span>. According to the repository description, the dataset has been used to teach students about Power BI and Python.</p>
<p>The dataset has two notable projects linked to it. Both are written in Python, and neither uses hierarchical models to analyze the fatality rate trend. Both include some exploratory data analysis, but since these are in Python we wrote our own analysis code in R.</p>
</section>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<section id="crashes-over-time" class="level2">
<h2 class="anchored" data-anchor-id="crashes-over-time">Crashes Over Time</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 1: Number of crashes - data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fig1 <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_crashes =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n_crashes)) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Crashes (Data)"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Number of Crashes"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 2: Number of crashes - trend</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>fig2 <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_crashes =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n_crashes)) <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Crashes (Trend)"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Number of Crashes"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>fig1 <span class="sc">+</span> fig2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/num-of-crashes-1.png" class="img-fluid figure-img" width="1152"></p>
<figcaption>Temporal trends in aviation accidents</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fatalities-over-time" class="level2">
<h2 class="anchored" data-anchor-id="fatalities-over-time">Fatalities Over Time</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 3: Fatalities - data points</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>fig3 <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fatalities)) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fatalities (Data Points)"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Fatalities"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 4: Fatalities - trend</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>fig4 <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fatalities)) <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fatalities (Trend)"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Fatalities"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>fig3 <span class="sc">+</span> fig4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/fatalities-over-time-1.png" class="img-fluid figure-img" width="1152"></p>
<figcaption>Trends in aviation accidents</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fatality-rate-over-time" class="level2">
<h2 class="anchored" data-anchor-id="fatality-rate-over-time">Fatality Rate Over Time</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute yearly mean fatality rate</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>rate_ts <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_rate =</span> <span class="fu">mean</span>(fatality_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_rate =</span> <span class="fu">sd</span>(fatality_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">ifelse</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>, sd_rate <span class="sc">/</span> <span class="fu">sqrt</span>(n), <span class="cn">NA_real_</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 5: Fatality rate - data points</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>fig5 <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fatality_rate)) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fatality Rate (Data Points)"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Fatality Rate"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Figure 6: Fatality rate - trend</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>fig6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(rate_ts, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> mean_rate)) <span class="sc">+</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fatality Rate (Trend)"</span>,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Mean Fatality Rate"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>fig5 <span class="sc">+</span> fig6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/fatality-rate-over-time-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Mean fatality rate by year</figcaption>
</figure>
</div>
</div>
</div>
<!-- ```{r}
#| label: save-images
#| include: false

# Save all figures
ggsave("figures/crashes-data.pdf", fig1, width = 5, height = 3.5)
ggsave("figures/crashes-trend.pdf", fig2, width = 5, height = 3.5)
ggsave("figures/fatalities-data.pdf", fig3, width = 5, height = 3.5)
ggsave("figures/fatalities-trend.pdf", fig4, width = 5, height = 3.5)
ggsave("figures/fatality-rate-data.pdf", fig5, width = 5, height = 3.5)
ggsave("figures/fatality-rate-trend.pdf", fig6, width = 5, height = 3.5)
``` -->
<p>To conduct a modern analysis on plane crash fatalities, we do not want to include observations from far back in the history. We need some reasonable cutoff point that keeps sufficient amount of data and allows us to model modern aircraft data. The fatalities trend shows a turning point around 1975, so it is reasonable to choose that as our observation cutoff year. This filtering brings our total observation count from 5013 down to 2188, so we are still left with plenty of data. We also only include observations from manufacturers with at least 10 crashes present in the data to stabilize the no pooling and partial pooling models. This brought our data down to 1766 observations.</p>
<p>1975 is a good cutoff date, because it resembles a period that shares lots of characteristics with modern flight travel. The 1950s and 1960s saw an upsurge in commercial flights, aircraft carriers, and international flying routes <span class="citation" data-cites="airwaysmag_commercial_flight"><a href="#ref-airwaysmag_commercial_flight" role="doc-biblioref">[2]</a></span>. This upsurge was accompanied by great technological innovations. The most notable ones were the jet engine in the 1950s (safer and more reliable than the earlier piston engines) and the introduction of electronic instruments to the cockpit in the 1970s <span class="citation" data-cites="allianz_aviation_safety"><a href="#ref-allianz_aviation_safety" role="doc-biblioref">[3]</a></span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>len_before <span class="ot">&lt;-</span> <span class="fu">nrow</span>(crashes)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>crashes_filtered <span class="ot">&lt;-</span> crashes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">&gt;</span> <span class="dv">1975</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>len_after <span class="ot">&lt;-</span> <span class="fu">nrow</span>(crashes_filtered)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observations before filtering:"</span>, len_before, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observations before filtering: 5013 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observations after filtering:"</span>, len_after, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observations after filtering: 2188 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Rows removed:"</span>, len_before <span class="sc">-</span> len_after, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows removed: 2825 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>len_before <span class="ot">&lt;-</span> <span class="fu">nrow</span>(crashes_filtered)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>n_manufacturers_before <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(crashes_filtered<span class="sc">$</span>aircraft_manufacturer)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>min_crashes <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>crashes_filtered <span class="ot">&lt;-</span> crashes_filtered <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(aircraft_manufacturer) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;=</span> min_crashes) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>len_after <span class="ot">&lt;-</span> <span class="fu">nrow</span>(crashes_filtered)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>n_manufacturers_after <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(crashes_filtered<span class="sc">$</span>aircraft_manufacturer)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observations before filtering:"</span>, len_before, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observations before filtering: 2188 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observations after filtering:"</span>, len_after, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observations after filtering: 1766 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Rows removed:"</span>, len_before <span class="sc">-</span> len_after, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows removed: 422 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Manufacturers before filtering:"</span>, n_manufacturers_before, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Manufacturers before filtering: 304 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Manufacturers after filtering:"</span>, n_manufacturers_after, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Manufacturers after filtering: 40 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>crashes_filtered <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">1766</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1994.59</td>
<td style="text-align: right;">11.41</td>
<td style="text-align: right;">1976.0</td>
<td style="text-align: right;">1986.00</td>
<td style="text-align: right;">1994.00</td>
<td style="text-align: right;">2003.00</td>
<td style="text-align: right;">2024.00</td>
<td style="text-align: left;">▆▇▆▅▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">day</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.96</td>
<td style="text-align: right;">8.73</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">31.00</td>
<td style="text-align: left;">▇▇▇▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ground</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.89</td>
<td style="text-align: right;">92.80</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2750.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">fatalities</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">29.57</td>
<td style="text-align: right;">48.77</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">32.00</td>
<td style="text-align: right;">583.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">aboard</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.07</td>
<td style="text-align: right;">64.65</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">52.00</td>
<td style="text-align: right;">644.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">fatality_rate</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▂▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year_scaled</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: left;">▆▇▆▅▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="empirical-fatality-rates-by-manufacturer" class="level2">
<h2 class="anchored" data-anchor-id="empirical-fatality-rates-by-manufacturer">Empirical Fatality Rates by Manufacturer</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute empirical fatality rates by manufacturer (≥10 crashes)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>empirical_rates <span class="ot">&lt;-</span> crashes_filtered <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(aircraft_manufacturer) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_rate =</span> <span class="fu">mean</span>(fatality_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_rate =</span> <span class="fu">sd</span>(fatality_rate, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">ifelse</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>, sd_rate <span class="sc">/</span> <span class="fu">sqrt</span>(n), <span class="cn">NA_real_</span>),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower_ci =</span> mean_rate <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper_ci =</span> mean_rate <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_rate)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot empirical rates</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>empirical_rates <span class="sc">%&gt;%</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">aircraft_manufacturer =</span> <span class="fu">fct_reorder</span>(aircraft_manufacturer, mean_rate)) <span class="sc">%&gt;%</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean_rate, <span class="at">y =</span> aircraft_manufacturer)) <span class="sc">+</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower_ci, <span class="at">xmax =</span> upper_ci), <span class="at">height =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">mean</span>(crashes_filtered<span class="sc">$</span>fatality_rate), </span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Empirical Fatality Rates by Manufacturer"</span>,</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Data only (no pooling); dashed line = overall mean"</span>,</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fatality Rate"</span>, </span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Manufacturer"</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/model3-empirical-rates-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="data-modeling" class="level1">
<h1>Data Modeling</h1>
<p>We model airplane crash fatality rates using three Bayesian models, each making different assumptions about information sharing across manufacturers. All models treat the number of fatalities <span class="math inline">\(y_i\)</span> in crash <span class="math inline">\(i\)</span> as binomially distributed given the number of people aboard <span class="math inline">\(n_i\)</span> and a crash-specific fatality probability <span class="math inline">\(p_i\)</span>.</p>
<p>We use the logit link to constrain all predictions to <span class="math inline">\([0, 1]\)</span>:</p>
<p><span class="math display">\[\operatorname{logit}(p_i) = \ln\!\left(\frac{p_i}{1-p_i}\right)\]</span></p>
<p>When <span class="math inline">\(\eta_i\)</span> is a linear predictor, solving for <span class="math inline">\(p_i\)</span> gives:</p>
<p><span class="math display">\[p_i = \frac{\exp(\eta_i)}{1 + \exp(\eta_i)}\]</span></p>
<p>This allows linear predictors <span class="math inline">\(\eta_i \in (-\infty, \infty)\)</span> to produce valid fatality probabilities.</p>
<section id="complete-pooling-non-hierarchical" class="level2">
<h2 class="anchored" data-anchor-id="complete-pooling-non-hierarchical">Complete Pooling (Non-Hierarchical)</h2>
<p>A complete pooling model assumes all observations are drawn from a single global distribution. In our plane crash setting this means every crash follows the same distribution regardless of manufacturer or any other grouping:</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha + \beta \cdot \text{year\_scaled}_i
\end{align*}\]</span></p>
<p>The strength of this model is its simplicity; its weakness is that it cannot capture manufacturer-level differences.</p>
</section>
<section id="no-pooling-non-hierarchical" class="level2">
<h2 class="anchored" data-anchor-id="no-pooling-non-hierarchical">No Pooling (Non-Hierarchical)</h2>
<p>A no pooling model gives each manufacturer its own completely independent distribution, with no information shared across groups. With <span class="math inline">\(m[i]\)</span> denoting the manufacturer of crash <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha_{m[i]} + \beta_{m[i]} \cdot \text{year\_scaled}_i
\end{align*}\]</span></p>
<p>This captures manufacturer-level differences but risks overfitting for manufacturers with few crashes, since they cannot borrow information from others.</p>
</section>
<section id="partial-pooling-hierarchical" class="level2">
<h2 class="anchored" data-anchor-id="partial-pooling-hierarchical">Partial Pooling (Hierarchical)</h2>
<p>A partial pooling model combines both approaches: each manufacturer has its own parameters, but those parameters are drawn from a shared global distribution. This regularizes estimates for manufacturers with little data by pulling them toward the global mean:</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha_0 + \beta_0 \cdot \text{year\_scaled}_i + \alpha_{m[i]} + \beta_{m[i]} \cdot \text{year\_scaled}_i \\[0.5em]
\begin{bmatrix} \alpha_m \\ \beta_m \end{bmatrix} &amp;\sim \mathcal{N}\!\left(\begin{bmatrix} 0 \\ 0 \end{bmatrix},\, \boldsymbol{\Sigma}\right), \quad \boldsymbol{\Sigma} = \begin{bmatrix} \sigma_\alpha^2 &amp; \rho\,\sigma_\alpha\sigma_\beta \\ \rho\,\sigma_\alpha\sigma_\beta &amp; \sigma_\beta^2 \end{bmatrix}
\end{align*}\]</span></p>
<p>The manufacturer-level effects <span class="math inline">\(\alpha_m\)</span> and <span class="math inline">\(\beta_m\)</span> are drawn from a multivariate normal distribution, which solves the overfitting problem of no pooling by borrowing strength from the global distribution.</p>
</section>
<section id="prior-selection" class="level2">
<h2 class="anchored" data-anchor-id="prior-selection">Prior Selection</h2>
<section id="global-intercept" class="level3">
<h3 class="anchored" data-anchor-id="global-intercept">Global Intercept</h3>
<p>For the global intercept <span class="math inline">\(\alpha\)</span>, we use a weakly informative prior centered on the observed fatality rate of <span class="math inline">\(\approx 0.8\)</span>, transformed to the logit scale:</p>
<p><span class="math display">\[\operatorname{logit}(0.8) = \ln\!\left(\frac{0.8}{0.2}\right) \approx 1.386 \approx 1.4\]</span></p>
<p>We use <span class="math inline">\(\alpha \sim \mathcal{N}(1.4,\, 1)\)</span>. The standard deviation of 1 keeps the prior weakly informative without over-constraining the estimate.</p>
</section>
<section id="global-year-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="global-year-coefficient">Global Year Coefficient</h3>
<p>For the year coefficient <span class="math inline">\(\beta\)</span>, we use a more conservative prior. The fatality rate plot shows only a slight yearly trend, so we use <span class="math inline">\(\beta \sim \mathcal{N}(0,\, 0.5)\)</span>, yielding a 95% credible interval of approximately <span class="math inline">\([-1.0,\, 1.0]\)</span>.</p>
</section>
<section id="manufacturer-level-priors-no-pooling" class="level3">
<h3 class="anchored" data-anchor-id="manufacturer-level-priors-no-pooling">Manufacturer-Level Priors (No Pooling)</h3>
<p>For the manufacturer-specific intercepts and slopes in the no pooling model, we use <span class="math inline">\(\mathcal{N}(0,\, 1)\)</span> — a safe, weakly informative choice that allows the data to dominate while keeping estimates in a reasonable range. brms requires a single prior class for all manufacturer-level coefficients, making it impractical to set manufacturer-specific priors.</p>
</section>
<section id="group-level-standard-deviation-partial-pooling" class="level3">
<h3 class="anchored" data-anchor-id="group-level-standard-deviation-partial-pooling">Group-Level Standard Deviation (Partial Pooling)</h3>
<p>For the group-level standard deviation <span class="math inline">\(\sigma\)</span> in the hierarchical model, we observe that manufacturer fatality rates fall roughly between 0.6 and 0.95 across all manufacturers. Assuming this range covers <span class="math inline">\(\pm 2\sigma\)</span> on the logit scale:</p>
<p><span class="math display">\[\sigma \approx \frac{\operatorname{logit}(0.95) - \operatorname{logit}(0.6)}{4} \approx 0.635\]</span></p>
<p>We use a half-normal prior <span class="math inline">\(\sigma \sim \mathcal{N}^+(0,\, 0.6)\)</span>, whose expected value is <span class="math inline">\(E[X] = 0.6\sqrt{2/\pi} \approx 0.479\)</span>.</p>
</section>
<section id="correlation-coefficient-rho" class="level3">
<h3 class="anchored" data-anchor-id="correlation-coefficient-rho">Correlation Coefficient <span class="math inline">\(\rho\)</span></h3>
<p>For the correlation <span class="math inline">\(\rho\)</span> between manufacturer-level intercepts and slopes, we use <span class="math inline">\(\rho \sim \text{LKJ}(2)\)</span>. The LKJ distribution is designed for correlation matrices. With shape parameter <span class="math inline">\(\eta = 2 &gt; 1\)</span>, the prior is skeptical of extreme correlations, producing a bell-shaped distribution centered at zero.</p>
</section>
</section>
</section>
<section id="complete-pooling-non-hierarchical-model" class="level1">
<h1>Complete pooling (non-hierarchical model)</h1>
<section id="complete-pooling-model" class="level2">
<h2 class="anchored" data-anchor-id="complete-pooling-model">Complete Pooling Model</h2>
<p>With <span class="math inline">\(i\)</span> representing individual crashes, <span class="math inline">\(n_i\)</span> representing the number of people aboard, and <span class="math inline">\(p_i\)</span> representing the fatality probability of a crash, the model is:</p>
<p><span class="math display">\[\begin{align*}
\text{Likelihood:} \quad &amp; \\
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha + \beta \cdot \text{year\_scaled}_i \\[1em]
\text{Priors:} \quad &amp; \\
\alpha &amp;\sim \mathcal{N}(1.4,\, 1) \\
\beta &amp;\sim \mathcal{N}(0,\, 0.5)
\end{align*}\]</span></p>
<p>The complete pooling model is the simplest of our three models. The model assumes that each manufacturer shares the same intercept and linear coefficient. The weakness of this model is that it is not able to capture the potential differences between the manufacturers.</p>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>complete_pool_formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  fatalities <span class="sc">|</span> <span class="fu">trials</span>(aboard) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> year_scaled,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="fl">1.4</span>, <span class="dv">1</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.5</span>), <span class="at">class =</span> b)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>complete_pool_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> complete_pool_formula,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> priors,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> crashes_filtered,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"cmdstanr"</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Running MCMC with 4 parallel chains...

Chain 1 finished in 1.1 seconds.
Chain 2 finished in 1.2 seconds.
Chain 3 finished in 1.2 seconds.
Chain 4 finished in 1.3 seconds.

All 4 chains finished successfully.
Mean chain execution time: 1.2 seconds.
Total execution time: 1.5 seconds.</code></pre>
</div>
</div>
</section>
<section id="convergence-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="convergence-diagnostics">Convergence Diagnostics</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(complete_pool_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: binomial 
  Links: mu = logit 
Formula: fatalities | trials(aboard) ~ 1 + year_scaled 
   Data: crashes_filtered (Number of observations: 1766) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept       0.81      0.02     0.78     0.84 1.00     3641     2792
year_scaled    -0.18      0.02    -0.21    -0.15 1.00     3901     2809

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>The <span class="math inline">\(\hat{R}\)</span> value for both the intercept term and the year coefficient is 1.00, indicating almost perfect chain overlapping. For both parameters, the bulk ESS values are over 3000 and the tail ESS values are over 2000. These values are great and definitely sufficient. The model had no divergences.</p>
</section>
<section id="posterior-predictive-check" class="level3">
<h3 class="anchored" data-anchor-id="posterior-predictive-check">Posterior Predictive Check</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(complete_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"ecdf_overlay"</span>) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Complete Pool — ECDF overlay"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/complete_pool_model_fit_check-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(complete_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Complete Pool — mean comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/complete_pool_model_fit_check-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(complete_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"sd"</span>) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Complete Pool — SD comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/complete_pool_model_fit_check-3.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The complete pooling model ECDF follows the observed ECDF better at low fatalities than the no pooling model, but it still struggles in the 25–100 fatalities region.</p>
<p>The mean comparison plot shows that the observed mean is almost at the exact center of the model simulated fatalities distribution, meaning that this model also estimates the overall fatality rate correctly.</p>
<p>The standard deviation comparison plot shows that this model is also under-dispersed, but the effect is smaller than with the no pooling model.</p>
</section>
<section id="predictions-over-time" class="level3">
<h3 class="anchored" data-anchor-id="predictions-over-time">Predictions Over Time</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_scaled =</span> <span class="fu">seq</span>(<span class="fu">min</span>(crashes_filtered<span class="sc">$</span>year_scaled),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">max</span>(crashes_filtered<span class="sc">$</span>year_scaled),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">length.out =</span> <span class="dv">100</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">aboard =</span> <span class="fu">round</span>(<span class="fu">mean</span>(crashes_filtered<span class="sc">$</span>aboard))</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> pred_data <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_epred_draws</span>(complete_pool_model, <span class="at">ndraws =</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.epred_rate =</span> .epred <span class="sc">/</span> aboard)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_lineribbon</span>(</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> predictions,</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> year_scaled, <span class="at">y =</span> .epred_rate),</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="fl">0.95</span>),</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> crashes_filtered,</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> year_scaled, <span class="at">y =</span> fatality_rate),</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.2</span>,</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Complete Pooling Model: Fatality Rate Over Time"</span>,</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Predictions for flights with "</span>,</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">round</span>(<span class="fu">mean</span>(crashes_filtered<span class="sc">$</span>aboard)), <span class="st">" people aboard (mean)"</span>),</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year (Standardized)"</span>,</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Fatality Rate"</span>,</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Credible Interval"</span></span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/complete_pool_model_visualisation-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prior-sensitivity-analysis" class="level3">
<h3 class="anchored" data-anchor-id="prior-sensitivity-analysis">Prior Sensitivity Analysis</h3>
<p>We conduct a prior sensitivity analysis on this model by trying out 3 different prior settings and comparing the estimated parameters. The priors we are using are:</p>
<ul>
<li><strong>Model prior:</strong> Intercept prior: <span class="math inline">\(\mathcal{N}(1.4, 1)\)</span>, year coefficient prior: <span class="math inline">\(\mathcal{N}(0, 0.5)\)</span> (same as the model).</li>
<li><strong>Wide prior:</strong> Intercept prior: <span class="math inline">\(\mathcal{N}(1.4, 3)\)</span>, year coefficient prior: <span class="math inline">\(\mathcal{N}(0, 1.5)\)</span> (3 times as wide for both).</li>
<li><strong>Shifted prior:</strong> Intercept prior: <span class="math inline">\(\mathcal{N}(3.4, 1)\)</span>, year coefficient prior: <span class="math inline">\(\mathcal{N}(2, 0.5)\)</span> (both priors shifted by 2 to the right).</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Prior Distribution</th>
<th><span class="math inline">\(\alpha\)</span></th>
<th><span class="math inline">\(\beta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model prior</td>
<td>0.81</td>
<td>−0.18</td>
</tr>
<tr class="even">
<td>Wide prior</td>
<td>0.81</td>
<td>−0.18</td>
</tr>
<tr class="odd">
<td>Shifted prior</td>
<td>0.81</td>
<td>−0.18</td>
</tr>
</tbody>
</table>
<p>The parameters are identical for all three priors. From these results it can be concluded that the model is very insensitive to the prior choice.</p>
</section>
</section>
</section>
<section id="no-pooling-non-hierarchical-model" class="level1">
<h1>No pooling (non-hierarchical model)</h1>
<section id="no-pooling-model" class="level2">
<h2 class="anchored" data-anchor-id="no-pooling-model">No Pooling Model</h2>
<p>This model treats every airplane manufacturer as their own independent entity, without sharing any information across any other possible grouping in the data. With <span class="math inline">\(i\)</span> being the index of a plane crash and <span class="math inline">\(m[i]\)</span> being the manufacturer <span class="math inline">\(m\)</span> for crash <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[\begin{align*}
\text{Likelihood:} \quad &amp; \\
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha_{m[i]} + \beta_{m[i]} \cdot \text{year\_scaled}_i \\[1em]
\text{Priors:} \quad &amp; \\
\alpha_m &amp;\sim \mathcal{N}(0,\, 1) \quad \text{for } m = 1, \ldots, M \\
\beta_m &amp;\sim \mathcal{N}(0,\, 1) \quad \text{for } m = 1, \ldots, M
\end{align*}\]</span></p>
<p>This means that the model assumes that each crash has its own fatality rate based on the manufacturer and the year, and crashes from other manufacturers do not influence each other in any way. With this model, the estimates for manufacturers with only a few crashes in the data become unstable, because they can’t borrow information from other manufacturers.</p>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>no_pool_formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    fatalities <span class="sc">|</span> <span class="fu">trials</span>(aboard) <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> aircraft_manufacturer <span class="sc">+</span> aircraft_manufacturer<span class="sc">:</span>year_scaled,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> b)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>no_pool_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> no_pool_formula,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> priors,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> crashes_filtered,</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">backend =</span> <span class="st">"cmdstanr"</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Running MCMC with 4 parallel chains...

Chain 4 finished in 18.2 seconds.
Chain 1 finished in 18.6 seconds.
Chain 2 finished in 19.7 seconds.
Chain 3 finished in 20.5 seconds.

All 4 chains finished successfully.
Mean chain execution time: 19.2 seconds.
Total execution time: 20.5 seconds.</code></pre>
</div>
</div>
</section>
<section id="convergence-diagnostics-1" class="level3">
<h3 class="anchored" data-anchor-id="convergence-diagnostics-1">Convergence Diagnostics</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(no_pool_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: binomial 
  Links: mu = logit 
Formula: fatalities | trials(aboard) ~ 0 + aircraft_manufacturer + aircraft_manufacturer:year_scaled 
   Data: crashes_filtered (Number of observations: 1766) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
                                                   Estimate Est.Error l-95% CI
aircraft_manufacturerAerospatiale                      1.73      0.54     0.70
aircraft_manufacturerAirbus                            0.09      0.07    -0.05
aircraft_manufacturerAntonov                           1.68      0.08     1.52
aircraft_manufacturerATR                               0.35      0.42    -0.46
aircraft_manufacturerBeechcraft                        1.84      0.44     1.01
aircraft_manufacturerBell                              1.94      0.40     1.18
aircraft_manufacturerBoeing                            0.72      0.03     0.67
aircraft_manufacturerBritishAerospace                 -0.75      0.44    -1.60
aircraft_manufacturerBritten                           1.26      0.28     0.73
aircraft_manufacturerBrittenNorman                     0.72      0.37    -0.01
aircraft_manufacturerCanadair                          0.35      0.53    -0.68
aircraft_manufacturerCASA                              1.51      0.42     0.69
aircraft_manufacturerCASA212Aviocar                   -0.24      0.47    -1.16
aircraft_manufacturerCessna                            1.52      0.44     0.68
aircraft_manufacturerConvair                           0.90      0.22     0.48
aircraft_manufacturerDeHavilland                       1.75      0.30     1.17
aircraft_manufacturerdeHavillandCanada                 0.91      0.11     0.69
aircraft_manufacturerDornier                          -0.09      0.47    -0.99
aircraft_manufacturerDouglas                           1.40      0.11     1.17
aircraft_manufacturerEmbraer                           1.25      0.37     0.52
aircraft_manufacturerEmbraer110P1                      2.00      0.50     1.04
aircraft_manufacturerFairchild                         3.16      0.31     2.57
aircraft_manufacturerFokker                            1.97      0.10     1.77
aircraft_manufacturerGrumman                          -0.03      0.36    -0.71
aircraft_manufacturerHawkerSiddeley                    0.39      0.19     0.02
aircraft_manufacturerIlyushin                          1.84      0.10     1.64
aircraft_manufacturerLearjet                           1.31      0.66     0.04
aircraft_manufacturerLet                               0.09      0.40    -0.69
aircraft_manufacturerLockheed                          0.16      0.07     0.03
aircraft_manufacturerMcDonnellDouglas                  0.05      0.04    -0.04
aircraft_manufacturerMi                               -0.84      0.34    -1.51
aircraft_manufacturerMil                               4.33      0.36     3.64
aircraft_manufacturerPilatus                           1.05      0.60    -0.08
aircraft_manufacturerPiper                             1.61      0.39     0.87
aircraft_manufacturerShorts                           -0.25      0.39    -0.97
aircraft_manufacturerSikorsky                          0.77      0.21     0.37
aircraft_manufacturerSwearingen                        2.34      0.56     1.23
aircraft_manufacturerTupolev                           0.98      0.06     0.86
aircraft_manufacturerVickersViscount                   2.42      0.34     1.77
aircraft_manufacturerYakovlev                          0.60      0.15     0.29
aircraft_manufacturerAerospatiale:year_scaled         -0.14      0.54    -1.20
aircraft_manufacturerAirbus:year_scaled                0.04      0.05    -0.07
aircraft_manufacturerAntonov:year_scaled              -0.22      0.07    -0.36
aircraft_manufacturerATR:year_scaled                   0.55      0.25     0.06
aircraft_manufacturerBeechcraft:year_scaled            0.43      0.42    -0.38
aircraft_manufacturerBell:year_scaled                  0.81      0.46    -0.05
aircraft_manufacturerBoeing:year_scaled               -0.34      0.03    -0.39
aircraft_manufacturerBritishAerospace:year_scaled      1.32      0.47     0.41
aircraft_manufacturerBritten:year_scaled              -0.05      0.29    -0.63
aircraft_manufacturerBrittenNorman:year_scaled         0.32      0.37    -0.41
aircraft_manufacturerCanadair:year_scaled              0.66      0.37    -0.06
aircraft_manufacturerCASA:year_scaled                  0.16      0.36    -0.54
aircraft_manufacturerCASA212Aviocar:year_scaled        2.07      0.60     0.90
aircraft_manufacturerCessna:year_scaled               -0.75      0.47    -1.65
aircraft_manufacturerConvair:year_scaled              -0.65      0.26    -1.16
aircraft_manufacturerDeHavilland:year_scaled          -0.22      0.28    -0.77
aircraft_manufacturerdeHavillandCanada:year_scaled     0.15      0.11    -0.07
aircraft_manufacturerDornier:year_scaled               1.04      0.38     0.30
aircraft_manufacturerDouglas:year_scaled              -0.37      0.16    -0.69
aircraft_manufacturerEmbraer:year_scaled              -0.43      0.26    -0.95
aircraft_manufacturerEmbraer110P1:year_scaled         -0.17      0.61    -1.35
aircraft_manufacturerFairchild:year_scaled            -1.35      0.47    -2.24
aircraft_manufacturerFokker:year_scaled               -1.49      0.10    -1.69
aircraft_manufacturerGrumman:year_scaled               0.57      0.40    -0.22
aircraft_manufacturerHawkerSiddeley:year_scaled        0.03      0.26    -0.47
aircraft_manufacturerIlyushin:year_scaled             -0.07      0.10    -0.27
aircraft_manufacturerLearjet:year_scaled               0.71      0.59    -0.46
aircraft_manufacturerLet:year_scaled                   0.40      0.30    -0.20
aircraft_manufacturerLockheed:year_scaled              1.00      0.09     0.82
aircraft_manufacturerMcDonnellDouglas:year_scaled     -0.13      0.05    -0.24
aircraft_manufacturerMi:year_scaled                    1.86      0.29     1.30
aircraft_manufacturerMil:year_scaled                  -1.67      0.29    -2.25
aircraft_manufacturerPilatus:year_scaled               1.14      0.57     0.04
aircraft_manufacturerPiper:year_scaled                 0.12      0.44    -0.73
aircraft_manufacturerShorts:year_scaled                1.11      0.42     0.30
aircraft_manufacturerSikorsky:year_scaled              0.92      0.26     0.44
aircraft_manufacturerSwearingen:year_scaled           -0.73      0.42    -1.56
aircraft_manufacturerTupolev:year_scaled              -0.01      0.06    -0.13
aircraft_manufacturerVickersViscount:year_scaled       1.98      0.77     0.50
aircraft_manufacturerYakovlev:year_scaled              0.56      0.18     0.22
                                                   u-95% CI Rhat Bulk_ESS
aircraft_manufacturerAerospatiale                      2.81 1.00     4747
aircraft_manufacturerAirbus                            0.23 1.00     3881
aircraft_manufacturerAntonov                           1.84 1.00     4704
aircraft_manufacturerATR                               1.16 1.00     5518
aircraft_manufacturerBeechcraft                        2.72 1.00     4993
aircraft_manufacturerBell                              2.73 1.00     5577
aircraft_manufacturerBoeing                            0.78 1.00     5567
aircraft_manufacturerBritishAerospace                  0.10 1.00     5224
aircraft_manufacturerBritten                           1.82 1.00     4878
aircraft_manufacturerBrittenNorman                     1.47 1.00     5396
aircraft_manufacturerCanadair                          1.40 1.00     5786
aircraft_manufacturerCASA                              2.35 1.00     4962
aircraft_manufacturerCASA212Aviocar                    0.67 1.00     5992
aircraft_manufacturerCessna                            2.38 1.00     5434
aircraft_manufacturerConvair                           1.33 1.00     5522
aircraft_manufacturerDeHavilland                       2.35 1.00     5343
aircraft_manufacturerdeHavillandCanada                 1.12 1.00     5440
aircraft_manufacturerDornier                           0.79 1.00     4284
aircraft_manufacturerDouglas                           1.62 1.00     5141
aircraft_manufacturerEmbraer                           1.99 1.00     5328
aircraft_manufacturerEmbraer110P1                      2.96 1.00     5831
aircraft_manufacturerFairchild                         3.79 1.00     5244
aircraft_manufacturerFokker                            2.17 1.00     5480
aircraft_manufacturerGrumman                           0.66 1.00     5634
aircraft_manufacturerHawkerSiddeley                    0.76 1.00     5878
aircraft_manufacturerIlyushin                          2.04 1.00     4950
aircraft_manufacturerLearjet                           2.65 1.00     6256
aircraft_manufacturerLet                               0.86 1.00     5045
aircraft_manufacturerLockheed                          0.30 1.00     4761
aircraft_manufacturerMcDonnellDouglas                  0.14 1.00     5539
aircraft_manufacturerMi                               -0.18 1.00     5518
aircraft_manufacturerMil                               5.05 1.00     5616
aircraft_manufacturerPilatus                           2.24 1.00     4946
aircraft_manufacturerPiper                             2.38 1.00     5644
aircraft_manufacturerShorts                            0.51 1.00     5593
aircraft_manufacturerSikorsky                          1.18 1.00     5416
aircraft_manufacturerSwearingen                        3.48 1.00     5954
aircraft_manufacturerTupolev                           1.09 1.00     5624
aircraft_manufacturerVickersViscount                   3.09 1.00     5859
aircraft_manufacturerYakovlev                          0.89 1.00     5685
aircraft_manufacturerAerospatiale:year_scaled          0.89 1.00     4951
aircraft_manufacturerAirbus:year_scaled                0.15 1.00     4166
aircraft_manufacturerAntonov:year_scaled              -0.07 1.00     5404
aircraft_manufacturerATR:year_scaled                   1.04 1.00     5408
aircraft_manufacturerBeechcraft:year_scaled            1.26 1.00     4928
aircraft_manufacturerBell:year_scaled                  1.74 1.00     6039
aircraft_manufacturerBoeing:year_scaled               -0.29 1.00     5440
aircraft_manufacturerBritishAerospace:year_scaled      2.23 1.00     5331
aircraft_manufacturerBritten:year_scaled               0.54 1.00     5314
aircraft_manufacturerBrittenNorman:year_scaled         1.06 1.00     5063
aircraft_manufacturerCanadair:year_scaled              1.39 1.00     5781
aircraft_manufacturerCASA:year_scaled                  0.85 1.00     5074
aircraft_manufacturerCASA212Aviocar:year_scaled        3.23 1.00     5826
aircraft_manufacturerCessna:year_scaled                0.17 1.00     5634
aircraft_manufacturerConvair:year_scaled              -0.14 1.00     5428
aircraft_manufacturerDeHavilland:year_scaled           0.34 1.00     5086
aircraft_manufacturerdeHavillandCanada:year_scaled     0.37 1.00     5531
aircraft_manufacturerDornier:year_scaled               1.80 1.00     4129
aircraft_manufacturerDouglas:year_scaled              -0.05 1.00     5423
aircraft_manufacturerEmbraer:year_scaled               0.08 1.00     4936
aircraft_manufacturerEmbraer110P1:year_scaled          1.04 1.00     5619
aircraft_manufacturerFairchild:year_scaled            -0.42 1.00     5031
aircraft_manufacturerFokker:year_scaled               -1.29 1.00     5282
aircraft_manufacturerGrumman:year_scaled               1.36 1.00     6058
aircraft_manufacturerHawkerSiddeley:year_scaled        0.54 1.00     5739
aircraft_manufacturerIlyushin:year_scaled              0.13 1.00     4788
aircraft_manufacturerLearjet:year_scaled               1.91 1.00     5934
aircraft_manufacturerLet:year_scaled                   0.98 1.00     5059
aircraft_manufacturerLockheed:year_scaled              1.17 1.00     4957
aircraft_manufacturerMcDonnellDouglas:year_scaled     -0.02 1.00     5721
aircraft_manufacturerMi:year_scaled                    2.44 1.00     5605
aircraft_manufacturerMil:year_scaled                  -1.11 1.00     5617
aircraft_manufacturerPilatus:year_scaled               2.30 1.00     5110
aircraft_manufacturerPiper:year_scaled                 0.98 1.00     5638
aircraft_manufacturerShorts:year_scaled                1.93 1.00     5583
aircraft_manufacturerSikorsky:year_scaled              1.44 1.00     5156
aircraft_manufacturerSwearingen:year_scaled            0.11 1.00     5913
aircraft_manufacturerTupolev:year_scaled               0.11 1.00     5401
aircraft_manufacturerVickersViscount:year_scaled       3.53 1.00     5626
aircraft_manufacturerYakovlev:year_scaled              0.91 1.00     5735
                                                   Tail_ESS
aircraft_manufacturerAerospatiale                      2991
aircraft_manufacturerAirbus                            2926
aircraft_manufacturerAntonov                           2805
aircraft_manufacturerATR                               3004
aircraft_manufacturerBeechcraft                        3324
aircraft_manufacturerBell                              3170
aircraft_manufacturerBoeing                            3083
aircraft_manufacturerBritishAerospace                  2746
aircraft_manufacturerBritten                           2867
aircraft_manufacturerBrittenNorman                     3164
aircraft_manufacturerCanadair                          3206
aircraft_manufacturerCASA                              2969
aircraft_manufacturerCASA212Aviocar                    3059
aircraft_manufacturerCessna                            3051
aircraft_manufacturerConvair                           3111
aircraft_manufacturerDeHavilland                       2783
aircraft_manufacturerdeHavillandCanada                 2967
aircraft_manufacturerDornier                           2906
aircraft_manufacturerDouglas                           3272
aircraft_manufacturerEmbraer                           3078
aircraft_manufacturerEmbraer110P1                      2952
aircraft_manufacturerFairchild                         3118
aircraft_manufacturerFokker                            3266
aircraft_manufacturerGrumman                           3251
aircraft_manufacturerHawkerSiddeley                    2733
aircraft_manufacturerIlyushin                          3135
aircraft_manufacturerLearjet                           3306
aircraft_manufacturerLet                               2763
aircraft_manufacturerLockheed                          3228
aircraft_manufacturerMcDonnellDouglas                  3237
aircraft_manufacturerMi                                3143
aircraft_manufacturerMil                               2930
aircraft_manufacturerPilatus                           3247
aircraft_manufacturerPiper                             3292
aircraft_manufacturerShorts                            3105
aircraft_manufacturerSikorsky                          2763
aircraft_manufacturerSwearingen                        2962
aircraft_manufacturerTupolev                           2953
aircraft_manufacturerVickersViscount                   3294
aircraft_manufacturerYakovlev                          3064
aircraft_manufacturerAerospatiale:year_scaled          3102
aircraft_manufacturerAirbus:year_scaled                3087
aircraft_manufacturerAntonov:year_scaled               2808
aircraft_manufacturerATR:year_scaled                   2869
aircraft_manufacturerBeechcraft:year_scaled            3107
aircraft_manufacturerBell:year_scaled                  3417
aircraft_manufacturerBoeing:year_scaled                3197
aircraft_manufacturerBritishAerospace:year_scaled      2790
aircraft_manufacturerBritten:year_scaled               2815
aircraft_manufacturerBrittenNorman:year_scaled         2767
aircraft_manufacturerCanadair:year_scaled              3040
aircraft_manufacturerCASA:year_scaled                  3175
aircraft_manufacturerCASA212Aviocar:year_scaled        3061
aircraft_manufacturerCessna:year_scaled                3140
aircraft_manufacturerConvair:year_scaled               3274
aircraft_manufacturerDeHavilland:year_scaled           2595
aircraft_manufacturerdeHavillandCanada:year_scaled     3247
aircraft_manufacturerDornier:year_scaled               3014
aircraft_manufacturerDouglas:year_scaled               3312
aircraft_manufacturerEmbraer:year_scaled               2826
aircraft_manufacturerEmbraer110P1:year_scaled          2871
aircraft_manufacturerFairchild:year_scaled             3023
aircraft_manufacturerFokker:year_scaled                3212
aircraft_manufacturerGrumman:year_scaled               2922
aircraft_manufacturerHawkerSiddeley:year_scaled        2928
aircraft_manufacturerIlyushin:year_scaled              3217
aircraft_manufacturerLearjet:year_scaled               3209
aircraft_manufacturerLet:year_scaled                   2850
aircraft_manufacturerLockheed:year_scaled              3094
aircraft_manufacturerMcDonnellDouglas:year_scaled      3575
aircraft_manufacturerMi:year_scaled                    3147
aircraft_manufacturerMil:year_scaled                   3004
aircraft_manufacturerPilatus:year_scaled               3014
aircraft_manufacturerPiper:year_scaled                 2996
aircraft_manufacturerShorts:year_scaled                2927
aircraft_manufacturerSikorsky:year_scaled              3246
aircraft_manufacturerSwearingen:year_scaled            2995
aircraft_manufacturerTupolev:year_scaled               3304
aircraft_manufacturerVickersViscount:year_scaled       3293
aircraft_manufacturerYakovlev:year_scaled              2951

Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>The <span class="math inline">\(\hat{R}\)</span> value for each of the parameters is 1.00, which means all coefficients converged properly. The bulk ESS values vary on the scale [4200, 5800] and the tail ESS values on the scale [2600, 3500]. These ESS values are far more than is needed for a reliable posterior estimation, so no problems there. The model had no divergences.</p>
</section>
<section id="posterior-predictive-check-1" class="level3">
<h3 class="anchored" data-anchor-id="posterior-predictive-check-1">Posterior Predictive Check</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(no_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"ecdf_overlay"</span>) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"No Pool — ECDF overlay"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/no_pool_model_fit_check-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(no_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"No Pool — mean comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/no_pool_model_fit_check-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(no_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"sd"</span>) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"No Pool — SD comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/no_pool_model_fit_check-3.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The ECDF (empirical cumulative distribution function) shows that the model is slightly off when compared to the real data. We can see that at the start, the observed ECDF rises faster and higher than the model ECDF, indicating that the model predicts less crashes with close to 0 fatalities. However, in the 25–100 fatalities area, the observed ECDF lags behind the model ECDF meaning that the model estimates more crashes that lead to those fatality numbers.</p>
<p>The mean comparison plot shows that the true fatalities mean lies close to the center of the model simulated fatalities distribution, meaning that the model estimates the overall mean fatality rate correctly.</p>
<p>The standard deviation comparison plot shows that the true fatalities standard deviation is much larger than what the model estimates. In other words, the model predicts too little variability and is under-dispersed.</p>
</section>
<section id="predictions-by-manufacturer" class="level3">
<h3 class="anchored" data-anchor-id="predictions-by-manufacturer">Predictions by Manufacturer</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>top_manufacturers <span class="ot">&lt;-</span> crashes_filtered <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(aircraft_manufacturer, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(aircraft_manufacturer)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">aircraft_manufacturer =</span> top_manufacturers,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_scaled =</span> <span class="fu">seq</span>(<span class="fu">min</span>(crashes_filtered<span class="sc">$</span>year_scaled),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">max</span>(crashes_filtered<span class="sc">$</span>year_scaled),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">aboard =</span> <span class="fu">round</span>(<span class="fu">mean</span>(crashes_filtered<span class="sc">$</span>aboard)))</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> pred_data <span class="sc">%&gt;%</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_epred_draws</span>(no_pool_model, <span class="at">ndraws =</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.epred_rate =</span> .epred <span class="sc">/</span> aboard)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_lineribbon</span>(</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> predictions,</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> year_scaled, <span class="at">y =</span> .epred_rate),</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="fl">0.95</span>),</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> crashes_filtered <span class="sc">%&gt;%</span> <span class="fu">filter</span>(aircraft_manufacturer <span class="sc">%in%</span> top_manufacturers),</span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> year_scaled, <span class="at">y =</span> fatality_rate),</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.2</span>,</span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> aircraft_manufacturer, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span></span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"No Pooling Model: Manufacturer-Specific Fatality Rates"</span>,</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Each manufacturer has independent intercept and slope (top 9 by crash count)"</span>,</span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year (Standardized)"</span>,</span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Fatality Rate"</span>,</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Credible Interval"</span></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/no_pool_model_visualisation-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prior-sensitivity-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="prior-sensitivity-analysis-1">Prior Sensitivity Analysis</h3>
<p>We conduct a prior sensitivity analysis on this model by trying out 3 different priors and comparing the estimated parameters of 4 manufacturers. The priors we are using are:</p>
<ul>
<li><strong>Model prior:</strong> <span class="math inline">\(\mathcal{N}(0, 1)\)</span> (same as the model).</li>
<li><strong>Wide prior:</strong> <span class="math inline">\(\mathcal{N}(0, 3)\)</span> (a much wider distribution).</li>
<li><strong>Shifted prior:</strong> <span class="math inline">\(\mathcal{N}(2, 1)\)</span> (shifted to the right).</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Prior Distribution</th>
<th>Manufacturer</th>
<th><span class="math inline">\(\alpha\)</span></th>
<th><span class="math inline">\(\beta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model <span class="math inline">\(\mathcal{N}(0, 1)\)</span></td>
<td>Boeing</td>
<td>0.72</td>
<td>−0.34</td>
</tr>
<tr class="even">
<td></td>
<td>Bell</td>
<td>1.94</td>
<td>0.82</td>
</tr>
<tr class="odd">
<td></td>
<td>Lockheed</td>
<td>0.16</td>
<td>1.00</td>
</tr>
<tr class="even">
<td></td>
<td>Mil</td>
<td>4.34</td>
<td>−1.67</td>
</tr>
<tr class="odd">
<td>Wide <span class="math inline">\(\mathcal{N}(0, 3)\)</span></td>
<td>Boeing</td>
<td>0.72</td>
<td>−0.34</td>
</tr>
<tr class="even">
<td></td>
<td>Bell</td>
<td>2.20</td>
<td>0.63</td>
</tr>
<tr class="odd">
<td></td>
<td>Lockheed</td>
<td>0.16</td>
<td>1.00</td>
</tr>
<tr class="even">
<td></td>
<td>Mil</td>
<td>5.16</td>
<td>−2.30</td>
</tr>
<tr class="odd">
<td>Shifted <span class="math inline">\(\mathcal{N}(2, 1)\)</span></td>
<td>Boeing</td>
<td>0.72</td>
<td>−0.34</td>
</tr>
<tr class="even">
<td></td>
<td>Bell</td>
<td>1.96</td>
<td>0.96</td>
</tr>
<tr class="odd">
<td></td>
<td>Lockheed</td>
<td>0.16</td>
<td>1.00</td>
</tr>
<tr class="even">
<td></td>
<td>Mil</td>
<td>4.40</td>
<td>−1.70</td>
</tr>
</tbody>
</table>
<p>We can see that the parameters do not vary much. For manufacturers with many observations in the data (Boeing: 248 observations, Lockheed: 106 observations), the parameters are identical for every prior. For manufacturers with a fewer number of observations (Mil: 41 observations, Bell: 33 observations), the parameter values show more variance:</p>
<p><span class="math display">\[\text{Mil: } \operatorname{Var}(\alpha) \approx 0.21,\quad \operatorname{Var}(\beta) \approx 0.11\]</span> <span class="math display">\[\text{Bell: } \operatorname{Var}(\alpha) \approx 0.02,\quad \operatorname{Var}(\beta) \approx 0.03\]</span></p>
<p>These variances are tolerable and still show the same trend, just in different strengths. The results show that the model is stable under reasonable prior changes, and the main conclusions drawn from the model do not depend on the chosen prior.</p>
</section>
</section>
</section>
<section id="partial-pooling-hierarchical-model" class="level1">
<h1>Partial pooling (hierarchical model)</h1>
<section id="partial-pooling-model" class="level2">
<h2 class="anchored" data-anchor-id="partial-pooling-model">Partial Pooling Model</h2>
<p>For the partially pooled model, we are predicting both a population level intercept and coefficient (<span class="math inline">\(\alpha_0\)</span> and <span class="math inline">\(\beta_0\)</span>) and manufacturer level intercepts and coefficients (<span class="math inline">\(\alpha_{m[i]}\)</span> and <span class="math inline">\(\beta_{m[i]}\)</span>). The partial pooling model is a combination of the techniques used in the no pooling model and the complete pooling model. The no pooling method assumed that each manufacturer had their own intercept and coefficient and the complete pooling model assumed that all manufacturers have the same intercept and coefficient. The partial pooling assumes that both of these conditions hold.</p>
<p><span class="math display">\[\begin{align*}
\text{Likelihood:} \quad &amp; \\
y_i &amp;\sim \text{Binomial}(n_i, p_i) \\
\text{logit}(p_i) &amp;= \alpha_0 + \beta_0 \cdot \text{year\_scaled}_i + \alpha_{m[i]} + \beta_{m[i]} \cdot \text{year\_scaled}_i \\[1em]
\text{Random effects:} \quad &amp; \\
\begin{bmatrix} \alpha_m \\ \beta_m \end{bmatrix} &amp;\sim \mathcal{N}\!\left(\begin{bmatrix} 0 \\ 0 \end{bmatrix},\, \boldsymbol{\Sigma}\right), \quad \boldsymbol{\Sigma} = \begin{bmatrix} \sigma_\alpha^2 &amp; \rho\,\sigma_\alpha\sigma_\beta \\ \rho\,\sigma_\alpha\sigma_\beta &amp; \sigma_\beta^2 \end{bmatrix} \\[1em]
\text{Priors:} \quad &amp; \\
\alpha_0 &amp;\sim \mathcal{N}(1.4,\, 1) \\
\beta_0 &amp;\sim \mathcal{N}(0,\, 0.5) \\
\sigma_\alpha,\, \sigma_\beta &amp;\sim \mathcal{N}^+(0,\, 0.6) \\
\rho &amp;\sim \text{LKJ}(2)
\end{align*}\]</span></p>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hierarchical_formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  fatalities <span class="sc">|</span> <span class="fu">trials</span>(aboard) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> year_scaled <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> year_scaled <span class="sc">|</span> aircraft_manufacturer),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="fl">1.4</span>, <span class="dv">1</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.5</span>), <span class="at">class =</span> b),</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.6</span>), <span class="at">class =</span> sd),</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prior</span>(<span class="fu">lkj</span>(<span class="dv">2</span>), <span class="at">class =</span> cor)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>partial_pool_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> hierarchical_formula,</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> priors,</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> crashes_filtered,</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>),</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"cmdstanr"</span></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Running MCMC with 4 parallel chains...

Chain 4 finished in 71.4 seconds.
Chain 2 finished in 73.1 seconds.
Chain 3 finished in 80.4 seconds.
Chain 1 finished in 91.2 seconds.

All 4 chains finished successfully.
Mean chain execution time: 79.0 seconds.
Total execution time: 91.3 seconds.</code></pre>
</div>
</div>
</section>
<section id="convergence-diagnostics-2" class="level3">
<h3 class="anchored" data-anchor-id="convergence-diagnostics-2">Convergence Diagnostics</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(partial_pool_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: binomial 
  Links: mu = logit 
Formula: fatalities | trials(aboard) ~ 1 + year_scaled + (1 + year_scaled | aircraft_manufacturer) 
   Data: crashes_filtered (Number of observations: 1766) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Multilevel Hyperparameters:
~aircraft_manufacturer (Number of levels: 40) 
                           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
sd(Intercept)                  1.22      0.14     0.97     1.51 1.00     1189
sd(year_scaled)                0.92      0.12     0.71     1.15 1.01      824
cor(Intercept,year_scaled)    -0.75      0.08    -0.87    -0.56 1.00     1013
                           Tail_ESS
sd(Intercept)                  2115
sd(year_scaled)                1529
cor(Intercept,year_scaled)     1649

Regression Coefficients:
            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept       1.27      0.20     0.88     1.66 1.00      441      971
year_scaled     0.02      0.15    -0.28     0.32 1.00      458     1138

Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc_plot</span>(partial_pool_model, <span class="at">type =</span> <span class="st">"trace"</span>,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"b_Intercept"</span>, <span class="st">"b_year_scaled"</span>,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"sd_aircraft_manufacturer__Intercept"</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"sd_aircraft_manufacturer__year_scaled"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/partial_pool_convergence-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The partial pooling model MCMC converged well with all <span class="math inline">\(\hat{R}\)</span> values smaller or equal to 1.01:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th><span class="math inline">\(\hat{R}\)</span></th>
<th>Bulk ESS</th>
<th>Tail ESS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\sigma_\alpha\)</span> (SD Intercept)</td>
<td>1.00</td>
<td>875</td>
<td>1707</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma_\beta\)</span> (SD year_scaled)</td>
<td>1.01</td>
<td>779</td>
<td>1184</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\rho\)</span> (Correlation)</td>
<td>1.00</td>
<td>961</td>
<td>1537</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha_0\)</span> (Intercept)</td>
<td>1.01</td>
<td>511</td>
<td>959</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_0\)</span> (year_scaled)</td>
<td>1.00</td>
<td>516</td>
<td>951</td>
</tr>
</tbody>
</table>
<p>Even though our process converged, the low ESS values are troublesome. Both bulk ESS and tail ESS values should be over 1000 in an ideal case. The models ESS values are relatively close to 1000 for the standard deviation and correlation parameters, but are far away from ideal for the intercept <span class="math inline">\(\alpha_0\)</span> and the coefficient <span class="math inline">\(\beta_0\)</span>. We tried doubling the warmup and iteration counts to 1000 and 4000 respectively, but the ESS numbers stay the same. This means that especially for <span class="math inline">\(\alpha_0\)</span> and <span class="math inline">\(\beta_0\)</span>, we don’t have enough independent samples for truly reliable posterior estimates.</p>
</section>
<section id="posterior-predictive-check-2" class="level3">
<h3 class="anchored" data-anchor-id="posterior-predictive-check-2">Posterior Predictive Check</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(partial_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"ecdf_overlay"</span>) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Partial Pool — ECDF overlay"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/partial_pool_ppc-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(partial_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Partial Pool — mean comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/partial_pool_ppc-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(partial_pool_model, <span class="at">ndraws =</span> <span class="dv">100</span>, <span class="at">type =</span> <span class="st">"stat"</span>, <span class="at">stat =</span> <span class="st">"sd"</span>) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Partial Pool — SD comparison"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/partial_pool_ppc-3.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The ECDF of the partially pooled model matches the original observations fairly well. Same for the observed mean. The standard deviation comparison has the same problem as the other two models: it is under-dispersed.</p>
</section>
<section id="prior-sensitivity-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="prior-sensitivity-analysis-2">Prior Sensitivity Analysis</h3>
<p>For the partial pooling model, we analyse how changing our prior assumptions on how similar manufacturers are affects the posterior predictions. We do this by using three different priors for our standard deviations <span class="math inline">\(\sigma\)</span>:</p>
<ul>
<li><strong>Baseline:</strong> <span class="math inline">\(\sigma \sim \mathcal{N}^+(0, 0.6)\)</span> (original)</li>
<li><strong>Tight:</strong> <span class="math inline">\(\sigma \sim \mathcal{N}^+(0, 0.3)\)</span> (assumes manufacturers more similar)</li>
<li><strong>Wide:</strong> <span class="math inline">\(\sigma \sim \mathcal{N}^+(0, 1.2)\)</span> (assumes manufacturers differ more)</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Prior Scenario</th>
<th>Intercept Mean</th>
<th>Year Effect Mean</th>
<th>SD Manufacturer Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline</td>
<td>1.271</td>
<td>0.019</td>
<td>1.205</td>
</tr>
<tr class="even">
<td>Tight</td>
<td>1.263</td>
<td>0.024</td>
<td>1.037</td>
</tr>
<tr class="odd">
<td>Wide</td>
<td>1.280</td>
<td>0.016</td>
<td>1.295</td>
</tr>
</tbody>
</table>
<p>The means don’t show noticeable effects from different prior choices. The standard deviation is affected by changing the prior distributions for it, but this is expected — the standard deviation priors should only affect the standard deviation posteriors. Thus we can conclude that our model is robust.</p>
</section>
</section>
</section>
<section id="model-comparison" class="level1">
<h1>Model comparison</h1>
<p>To compare the three models, we use LOO-CV (Leave-One-Out Cross-Validation), which has the basic idea of: 1) remove an observation <span class="math inline">\(i\)</span>, 2) train the model, 3) predict observation <span class="math inline">\(i\)</span>. Then measure how well the model performed and compare the models. We measure the ELPD (Expected Log Predictive Density) and SE (Standard Error) for all models and then compare them with each other. We use the partial pooling model as the baseline.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>no_pool_loo <span class="ot">&lt;-</span> <span class="fu">loo</span>(no_pool_model)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>complete_pool_loo <span class="ot">&lt;-</span> <span class="fu">loo</span>(complete_pool_model)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>partial_pool_loo <span class="ot">&lt;-</span> <span class="fu">loo</span>(partial_pool_model)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">loo_compare</span>(no_pool_loo, complete_pool_loo, partial_pool_loo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    elpd_diff se_diff
no_pool_model           0.0       0.0
partial_pool_model    -27.6      14.0
complete_pool_model -1974.0     691.8</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>elpd_diff</th>
<th>se_diff</th>
<th><span class="math inline">\(\lvert\text{elpd\_diff} / \text{se\_diff}\rvert\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>partial_pool_model</td>
<td>0.0</td>
<td>0.0</td>
<td>—</td>
</tr>
<tr class="even">
<td>no_pool_model</td>
<td>−16.5</td>
<td>13.3</td>
<td>1.24</td>
</tr>
<tr class="odd">
<td>complete_pool_model</td>
<td>−1944.8</td>
<td>692.3</td>
<td>2.81</td>
</tr>
</tbody>
</table>
<p>A good rule of thumb is that if <span class="math inline">\(|\text{elpd\_diff}| &lt; 1 \times \text{se\_diff}\)</span>, the models are close to equal, and if <span class="math inline">\(|\text{elpd\_diff}| &gt; 2 \times \text{se\_diff}\)</span>, there is a clear difference between the models. A higher ELPD value indicates better performance.</p>
<p>The no pooling model seems to perform slightly worse than the partial pooling model, but the ratio of 1.24 is still close to 1 and could just be due to random noise, so no clear conclusions can be drawn from this.</p>
<p>The complete pooling model, however, can be reported to perform significantly worse than the other two models. The reason for this is most likely that the model fails to capture the manufacturer level differences, and therefore predicts incorrectly for most crashes.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Although the partial pooling model performs best according to LOO cross-validation, none of the three models succeeds in accurately modeling the structure of the real data, as revealed by the posterior predictive check analysis.</p>
<p>The two non-hierarchical models have their obvious limitations, but the interesting question is: why does the hierarchical model fail? On paper, it should perform well, because it uses population level information as well as captures the manufacturer level differences. Evidently, it still has its limitations.</p>
<p>The problem with all of our models seemed to be that they were under-dispersed, meaning that they underestimated the variance. The reason for this mainly comes from our use of binomial likelihood for predicting the fatalities. The variance formula of binomial likelihood for an observation <span class="math inline">\(i\)</span> is</p>
<p><span class="math display">\[\operatorname{Var}(Y_i) = n_i p_i (1 - p_i)\]</span></p>
<p>This formula is fixed once <span class="math inline">\(n_i\)</span> and <span class="math inline">\(p_i\)</span> are known and is bounded by <span class="math inline">\(n_i / 4\)</span> (when <span class="math inline">\(p_i = 0.5\)</span>). The true variances in the observed data were shown to be much larger than the models’, because the binomial variance simply cannot reach the true variability values. As a potential improvement for the models, a different likelihood function that could combat this under-dispersion problem should be used.</p>
<p>Another reason that our models fail is much simpler. Airplane crashes simply cannot be modeled accurately, especially with so little information. There are countless factors that can affect the fatality rate of a crash and there is a lot of randomness included. One could try to add more predictors and see if it yields better results. But even with more predictors included, the results would still most likely be inaccurate, but perhaps better than what we reached.</p>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<p>In our report, we modeled fatality rate trends with hierarchical and non-hierarchical models. We used three types of models: complete pooling, no pooling and partial pooling models. From these models the partial pooling model performed the best with the no pooling model coming in a close second. We used LOO-CV to compare our models.</p>
<p>One of our research questions was whether there are differences in the fatality rates of manufacturers. The fact that the partial pooling and no pooling models performed well would suggest that fatalities are modeled better assuming that each manufacturer has their own parameters and distributions.</p>
<p>According to our prior sensitivity analysis, the models were quite unaffected by changes in priors. This means that our models are able to model the fatality rates well without the priors having too big of an effect on the model.</p>
<p>In our posterior predictive analysis, we noticed that our models weren’t capturing the variance of the original observations. The variance of our models was too small. This was due to the fixed maximum variance of the binomial model being too small to correctly model the real crash variance.</p>
</section>
<section id="self-reflection" class="level1">
<h1>Self Reflection</h1>
<p>The project was a great summary of the key concepts taught in the Bayesian Data Analysis course. During the course we acquired basic skills in Bayesian data analysis and during the project we got to use them in practice and deepen our understanding about the methods.</p>
<p>In this report we discussed things like hierarchical and non-hierarchical models, how to choose priors and test the effects of these priors on the predictions, how to run MCMC simulations and how to compare and evaluate the models these simulations suggest.</p>
<p>Running MCMC simulations is computationally expensive and the project showed the importance of access to cloud computing resources. Running the MCMC code could take over 30 minutes on old hardware while it took 5–10 minutes to run on modern cloud hardware in JupyterHub.</p>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-jogwums2023aircrashes" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Jogwums, <span>“Air crashes full data (1908-2024).”</span> Kaggle, 2024. Available: <a href="https://www.kaggle.com/datasets/jogwums/air-crashes-full-data-1908-2023">https://www.kaggle.com/datasets/jogwums/air-crashes-full-data-1908-2023</a></div>
</div>
<div id="ref-airwaysmag_commercial_flight" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Airways Magazine, <span>“The history of commercial flight: How global travel took off,”</span> <em>Airways Magazine</em>, Available: <a href="https://www.airwaysmag.com/legacy-posts/how-global-travel-took-off">https://www.airwaysmag.com/legacy-posts/how-global-travel-took-off</a></div>
</div>
<div id="ref-allianz_aviation_safety" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">Allianz Global Corporate &amp; Specialty, <span>“How aviation safety has improved,”</span> 2015, Available: <a href="https://commercial.allianz.com/news-and-insights/expert-risk-articles/how-aviation-safety-has-improved.html">https://commercial.allianz.com/news-and-insights/expert-risk-articles/how-aviation-safety-has-improved.html</a></div>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/AJBogo9\.github\.io\/bayesian-fatality-analysis\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>